### ISSUE TITLE
Razer Synapse 4.0 beta issue

### ISSUE THREAD

**Issue by Oliv93r** [sanraith/razer-taskbar#1]
As expected, the application no longer works after being accepted for the Synapse 4.0 beta. 

I'm wondering if there's some kind of patch available, even a Frankenstein'd Synapse 3.0 installation of including relevant components, libs, etc. If you need access to any Synapse 4.0 files to do this, feel free to let me know and I'll send you the files - miss my little taskbar indicator already! :( 

Anyway cheers mate, great little lightweight tool regardless.

**Comment by sanraith** [comment]
Hey,
I did not know of a version 4 until now, is this the "NEW RAZER SYNAPSE" from here? https://www.razer.com/eu-en/synapse-new
If it is, I'll take a look when I have some free time. Hopefully they have kept their good habit of verbose logging.

**Comment by sanraith** [comment]
Razer Synapse 4 beta is now supported in [v0.10.0](https://github.com/sanraith/razer-taskbar/releases/tag/v0.10.0).
