### ISSUE TITLE
Display battery percentage on system tray icon?

### ISSUE THREAD

**Issue by BooBerry** [sanraith/razer-taskbar#12]
Greetings! Nice work on this app, it sure helps having a visual indicator of the battery level without opening Synapse.

My question is, would it be possible for the app to have an option to either display a battery percentage over the battery icon or replace the battery icon with a percentage?

Thanks!

P.S. The green color of the battery icon can be a bit hard to see on light Windows themes, maybe a color changer may also be a good idea?

**Comment by sanraith** [comment]
Hey,
I'm not planning on adding digit display at the moment, but happy to merge a PR if somebody implements it.
I might do something about the light mode visibility in the future.

**Comment by sanraith** [comment]
Added numeric battery display in [v0.12.0](https://github.com/sanraith/razer-taskbar/releases/tag/v0.12.0).
