### ISSUE TITLE
Mousing over tray icon on primary display brings secondary out of fullscreen

### ISSUE THREAD

**Issue by justinjoseph-24** [sanraith/razer-taskbar#14]
Windows 11 Pro. Nvidia TI 4070 TI. When this happens, the full screen game on the secondary goes gets minimized, showing the desktop.  This behavior is consistent. Is there a way to show the battery percentage contextual popup without causing this? Update: There is a certain graphics mode activated when in full screen. This is when it triggfers.

**Comment by sanraith** [comment]
Hey,
This is an intresting issue. I'm just calling an electron API for the tooltip, so I might not be able to fix it on my side.
Lets say this is a +1 for Issue #12 to display the percentage within the icon, as that would solve your use case too.

**Comment by justinjoseph-24** [comment]
> Hey, This is an intresting issue. I'm just calling an electron API for the tooltip, so I might not be able to fix it on my side. Lets say this is a +1 for Issue #12 to display the percentage within the icon, as that would solve your use case too.

Great idea, and thanks for contributing this.

**Comment by sanraith** [comment]
Added numeric battery display in [v0.12.0](https://github.com/sanraith/razer-taskbar/releases/tag/v0.12.0).

**Comment by justinjoseph-24** [comment]
It works great! Thanks for making this improvement; very cool utility.
