### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by fofive** [sanraith/razer-taskbar#4]
When I right click on the taskbar icon, it says "No devices found." yet in the settings it sees my devices.

**Comment by sanraith** [comment]
Hey,
What version of the app are you using? What version of razer synapse are you using? Did it only broke recently, or did it never work for you? The behaviour you described refers to the app finding records of your device in the log, but the latest entry of it is being "disconnected". 

If you don't have the latest version of razer-taskbar yet, you can try installing it and see if that makes a difference.

If you already have the latest version, you can try this:
1. Exit razer-taskbar and Razer Synapse 
2. Based on the Synapse version you have, make a backup and delete the log file(s):
    - `%LOCALAPPDATA%\Razer\Synapse3\Log\Razer Synapse 3.log` for Razer Synapse 3
    - `%LOCALAPPDATA%\Razer\RazerAppEngine\User Data\systray_systrayv2.log` for Razer Synapse 4 
    (there may be multiple files with _1, _2,... suffixes, delete them all)
3. Start Razer Synapse
4. Start razer-taskbar
5. see if this fixes the issue

**Comment by sanraith** [comment]
Since then I ran into this and it seems to happen when the Synapse V4 creates a new logfile after my app starts watching a previous one. I'll add a fix to watch the new file when this happens. As a workaround, simply restarting the razer-taskbar fixes the issue.

**Comment by sanraith** [comment]
Fixed in [v0.10.4](https://github.com/sanraith/razer-taskbar/releases/tag/v0.10.4).
