### ISSUE TITLE
Mouse appears twice

### ISSUE THREAD

**Issue by mangoshaper** [sanraith/razer-taskbar#5]
Hi!

I have a Razer Viper V2 Pro and it appears twice in the drop down menu:
![Capture d'écran 2024-05-19 132953](https://github.com/sanraith/razer-taskbar/assets/170237473/6238bd58-0e91-4716-9c48-06f95d9ae913)

One works fine and the other one shows the _no device found_ icon: ![Capture d'écran 2024-05-19 133008](https://github.com/sanraith/razer-taskbar/assets/170237473/43acee59-6319-4cbe-aee1-80f0cb0a3ba6)

The issue is that even if I select the working one, after a few minutes it switches back to the non working one and I have to switch it back so often that it's annoying.
I've checked in my Device Manager if the mouse appears twice but no.
The problem occurs if I select the Auto option too.

My Razer Synapse version is 3.9.516: 
![image](https://github.com/sanraith/razer-taskbar/assets/170237473/179add8e-8b2c-4239-b930-fc16a9ff7494)
Razer Taskbar:
![image](https://github.com/sanraith/razer-taskbar/assets/170237473/fd06c9c8-583a-4768-af65-9e6025d32c5f)

Could you help me?

Thanks in advance,

Aurélien

**Comment by sanraith** [comment]
Hey,

Could you help me investigate this by showing some sections from your `%LOCALAPPDATA%\Razer\Synapse3\Log\Razer Synapse 3.log` file? My app only reacts to it when it sees `_OnBatteryLevelChanged`, `_OnDeviceLoaded` and `_OnDeviceRemoved` events. So when my app breaks for you, we could find the problem by checking these events around the time of the error.

I'm looking for sections like this:
```
2024-05-19 22:37:57.9028 INFO 15 _OnBatteryLevelChanged: device Name: Razer BlackShark V2 Pro
Product_ID: 1365 (0x555)
Edition_ID: 0 (0x0)
Vendor_ID: 5426 (0x1532)
Layout: 0 (0x0)
Serial_Number: XXXXXXXXXX
Firmware_Version: 2.5.3.0
Handle: 123456 (0x123456)
Type: 3
SKU_ID: 
RegionId: 0
Id: 0 level 42 state 1
```

**Comment by mangoshaper** [comment]
I am so sorry, I just figured it out...
It was the battery update delay set to 5 minutes.
After changing it to 1 sec the problem is no longer there.
